In [1]:
__author__ = "Atharva Muley"

In [2]:
import numpy as np
import math
import random

In [22]:
#Initialization
no_of_in = 2 #no of input nodes
no_of_hn = 3 #no of hidden nodes
no_of_on = 1 #no of output nodes

#Neural network layers 
#input_layer = np.zeros(no_of_in)
hidden_layer = np.zeros((2,no_of_hn))
output_layer = np.zeros((2,no_of_on))
print(hidden_layer)
print(output_layer)
#Note:using index 0 for Yin and index 1 for Yout 

[[0. 0. 0.]
 [0. 0. 0.]]
[[0.]
 [0.]]


In [4]:
#Weights for Neural Network
Wih = np.zeros((no_of_in,no_of_hn))
Who = np.zeros((no_of_hn,no_of_on))

In [12]:
Bh = np.zeros(no_of_hn)
Bo = np.zeros(no_of_on)

print(Bh)
print(Bo)

[0. 0. 0.]
[0.]


In [24]:
Cih = np.zeros((no_of_in,hidden_layer.size))
Cho = np.zeros((no_of_hn,no_of_on))
print(Cih)
print(Cho)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [5]:
#Assign random values to Weights
def randassign(a,b):
    return (b-a)*random.random() + a

m,n = Wih.shape
for i in range(m):
    for j in range(n):
        Wih[i,j] = randassign(-1,1)

print(Wih.shape)

m,n = Who.shape
for i in range(m):
    for j in range(n):
        Who[i,j] = randassign(-1,1)
        
print(Who.shape)

(2, 3)
(3, 1)


In [9]:
def sigmoid(x,derivative=False):
    if derivative:
         return x*(1-x) 
    return 1/(1+math.exp(-x))

def relu(x):
    if x > 0:
        return x
    else:
        return 0
        

In [16]:
def backpropagate(loss,LR,M,):
    '''global Who
    print(Who)
    m,n = Who.shape
    Wtemp = np.zeros(Who.shape)
    ''' 
    delta = 0
    for i in range(no_of_on):
        delta += loss*sigmoid(output_layer[0][i],derivative=True)
    
    for i in range(no_of_hn):
        Cho[i] = LR*delta*hidden_layer[0][i]
    
        
def loss(y1,y):
    return ((y-y1)**2/2)

def feed_forward(p,q):
    #Matrix multiplication for input and Hidden layer
    #for i in range(no_of_in):
    #   input_layer[i] = p[i]
    
    #Calculating sum and applying activation function for hidden nodes
    for i in range(no_of_hn):
        sum = 0 
        for j in range(no_of_in):
            sum = sum + x[i][j]*Wih[j][i]
            hidden_layer[0][i] = sum + Bh[i]
        hidden_layer[1][i] = sigmoid(sum)
        
            
    #Calculating sum and applying activation function for output nodes
    for i in range(no_of_on):
        sum = 0 
        for j in range(no_of_hn):
            sum = sum + hidden_layer[j]*Who[j][i]
            output_layer[0][i] = sum + Bo[i]
        output_layer[1][0] = sigmoid(sum)
    
    #Calculating error(loss) for current iteration
    error = loss(q,output_layer[1][0])
    return error[:]

    #LR = Learning Rate, M = Moumentum 
def fit(input_data,output,epochs,LR=0.5,M=0.9):
    
    if (len(input_data)!=len(output)):
        print("Input and Output dataset missmatch")
        return
    
    for i in range(len(input_data)):
        in_data = input_data[i]
        out_data = output[i]
        error = feed_forward(in_data,out_data)
        backpropagate(error,LR,M)

In [18]:
#feed_forward([0,0],[1]) 

backpropagate(0.125,0.5,0.9)

[[ 0.91504718]
 [-0.67746958]
 [ 0.66228306]]
THis is delta: 0.0
This is x: [0.91504718]
THis is delta: 0.0
This is x: [-0.67746958]
THis is delta: 0.0
This is x: [0.66228306]
[[0.]
 [0.]
 [0.]]
