In [1]:
__author__ = "Atharva Muley"

In [2]:
import numpy as np
import math
import random

In [3]:
#Initialization
no_of_in = 2 #no of input nodes
no_of_hn = 3 #no of hidden nodes
no_of_on = 1 #no of output nodes

#Neural network layers 
input_layer = np.zeros(no_of_in)
hidden_layer = np.zeros(no_of_hn)
output_layer = np.zeros(no_of_on)

In [4]:
#Weights for Neural Network
Wih = np.zeros((no_of_in,no_of_hn))
Who = np.zeros((no_of_hn,no_of_on))

In [5]:
#Assign random values to Weights
def randassign(a,b):
    return (b-a)*random.random() + a

m,n = Wih.shape
for i in range(m):
    for j in range(n):
        Wih[i,j] = randassign(-1,1)

print(Wih)

m,n = Who.shape
for i in range(m):
    for j in range(n):
        Who[i,j] = randassign(-1,1)
        
print(Who.shape)

[[-0.55535435 -0.60097485 -0.2185588 ]
 [ 0.07143233 -0.30166452  0.94718009]]
(3, 1)


In [6]:
Cih = np.zeros((input_layer.size,hidden_layer.size))
Cho = np.zeros((hidden_layer.size,output_layer.size))

In [7]:
def sigmoid(x):
    return 1/(1+math.exp(-x))

def relu(x):
    if x > 0:
        return x
    else:
        return 0
        

NameError: name 'Wtemp' is not defined

In [53]:
def backpropagate(loss,LR,M):
    global Who
    print(Who)
    m,n = Who.shape
    Wtemp = np.zeros(Who.shape)
    for i in range(no_of_hn):
        #Rate of Change
        delta = LR*loss*hidden_layer[i]
        print("THis is delta:",delta)
        x = Who[i] + delta + M*Cho[i]
        print("This is x:",x)
        Cho[i] = delta
    print(Wtemp)
#     print(Cho)
        
    
        
def loss(y1,y):
    return ((y-y1)**2/2)

def feed_forward(p,q):
    #Matrix multiplication for input and Hidden layer
    for i in range(no_of_in):
        input_layer[i] = p[i]
    
    #Calculating sum and applying activation function for hidden nodes
    for i in range(no_of_hn):
        sum = 0 
        for j in range(no_of_in):
            sum = sum + input_layer[j]*Wih[j][i]
        hidden_layer[i] = relu(sum)
        
            
    #Calculating sum and applying activation function for output nodes
    for i in range(no_of_on):
        sum = 0 
        for j in range(no_of_hn):
            sum = sum + hidden_layer[j]*Who[j][i]
        output_layer[i] = sigmoid(sum)
    
    #Calculating error(loss) for current iteration
    error = loss(q,output_layer[0])
    return error[:]

    #LR = Learning Rate, M = Moumentum 
def fit(input_data,output,epochs,LR=0.5,M=0.9):
    
    if (len(input_data)!=len(output)):
        print("input and output dataset missmatch")
        return
    
    for i in range(len(input_data)):
        in_data = input_data[i]
        out_data = data[i]
        error = feed_forward(in_data,out_data)
        backpropagate(error,LR,M)

In [54]:
feed_forward([0,0],[1])
backpropagate(0.125,0.5,0.9)

[[-0.04399123]
 [ 0.41834493]
 [ 0.70228966]]
THis is delta: 0.0
This is x: [-0.04399123]
THis is delta: 0.0
This is x: [0.41834493]
THis is delta: 0.0
This is x: [0.70228966]
[[0.]
 [0.]
 [0.]]
